-- EarlyBird - Postgres (Supabase) schema, ported from SQL Server.
-- Type map: nvarchar->TEXT, varchar(n)->VARCHAR(n), float->DOUBLE PRECISION, bit->BOOLEAN,
--   datetime2->TIMESTAMPTZ, int IDENTITY->GENERATED BY DEFAULT AS IDENTITY, SYSUTCDATETIME()->now().
-- RLS is ENABLED with NO policies on every table => the public Data API is deny-all.
-- Our jobs connect via the direct Postgres role (Session pooler), which BYPASSES RLS.

CREATE TABLE IF NOT EXISTS tbl_eb_universe (
  isin VARCHAR(12) PRIMARY KEY,
  yf_ticker VARCHAR(40), t212_ticker VARCHAR(40), name TEXT,
  country VARCHAR(4), currency VARCHAR(8), type VARCHAR(20),
  only_foreign_listing BOOLEAN NOT NULL DEFAULT false,
  active BOOLEAN NOT NULL DEFAULT true,
  first_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tbl_eb_fundamentals (
  yf_ticker VARCHAR(40) PRIMARY KEY, isin VARCHAR(12),
  as_of TIMESTAMPTZ NOT NULL DEFAULT now(),
  price DOUBLE PRECISION, currency VARCHAR(8), market_cap BIGINT,
  wk52_low DOUBLE PRECISION, wk52_high DOUBLE PRECISION, range_pct DOUBLE PRECISION,
  fwd_pe DOUBLE PRECISION, trailing_pe DOUBLE PRECISION, revenue_growth DOUBLE PRECISION,
  gross_margin DOUBLE PRECISION, profit_margin DOUBLE PRECISION, target_mean DOUBLE PRECISION,
  total_cash BIGINT, total_debt BIGINT,
  sector TEXT, industry TEXT, summary TEXT,
  fetch_ok BOOLEAN NOT NULL DEFAULT false, fetch_note TEXT
);

CREATE TABLE IF NOT EXISTS tbl_eb_moves (
  yf_ticker VARCHAR(40) PRIMARY KEY,
  price DOUBLE PRECISION, mv_1m DOUBLE PRECISION, mv_3m DOUBLE PRECISION, mv_6m DOUBLE PRECISION,
  as_of TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tbl_eb_news (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  yf_ticker VARCHAR(40) NOT NULL, news_key VARCHAR(200) NOT NULL,
  title TEXT, publisher TEXT, url TEXT, published TIMESTAMPTZ,
  catalyst BOOLEAN NOT NULL DEFAULT false, catalyst_terms TEXT,
  fetched_on TIMESTAMPTZ NOT NULL DEFAULT now(), catalyst_type TEXT,
  CONSTRAINT uq_eb_news UNIQUE (yf_ticker, news_key)
);

CREATE TABLE IF NOT EXISTS tbl_eb_sector_news (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sector TEXT NOT NULL, source TEXT, title TEXT, link TEXT,
  published TIMESTAMPTZ, summary TEXT, guid VARCHAR(300) NOT NULL,
  fetched_on TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_eb_secnews UNIQUE (sector, guid)
);

CREATE TABLE IF NOT EXISTS tbl_eb_pool (
  sector TEXT, yf_ticker VARCHAR(40), name TEXT, country VARCHAR(4),
  gics_sector TEXT, market_cap BIGINT, range_pct DOUBLE PRECISION,
  fwd_pe DOUBLE PRECISION, revenue_growth DOUBLE PRECISION, price DOUBLE PRECISION,
  fit_score INTEGER, matched TEXT, fit VARCHAR(8),
  refreshed_on TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tbl_eb_sa_13f (
  cik VARCHAR(12) NOT NULL, fund TEXT, period DATE NOT NULL, filed DATE,
  name TEXT NOT NULL, cusip VARCHAR(12), value BIGINT, shares BIGINT,
  CONSTRAINT uq_sa13f UNIQUE (cik, period, name, cusip)
);

CREATE TABLE IF NOT EXISTS tbl_eb_sector_keywords (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sector TEXT NOT NULL, keyword TEXT NOT NULL, kind VARCHAR(8) NOT NULL,
  tier VARCHAR(8), active BOOLEAN NOT NULL DEFAULT true,
  added_on TIMESTAMPTZ DEFAULT now(), source TEXT
);

CREATE TABLE IF NOT EXISTS tbl_eb_keyword_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts TIMESTAMPTZ NOT NULL DEFAULT now(), sector TEXT, keyword TEXT,
  action VARCHAR(20), detail TEXT, reason TEXT
);

CREATE TABLE IF NOT EXISTS tbl_eb_trump_news (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source VARCHAR(10) NOT NULL, title TEXT, link TEXT, published TIMESTAMPTZ,
  matched_ticker VARCHAR(40) NOT NULL DEFAULT '',   -- '' = unmatched (keeps UNIQUE usable)
  matched_name TEXT, in_universe BOOLEAN NOT NULL DEFAULT false,
  guid VARCHAR(320) NOT NULL, fetched_on TIMESTAMPTZ NOT NULL DEFAULT now(),
  sentiment VARCHAR(8), alerted BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT uq_eb_trump UNIQUE (guid, matched_ticker)
);

CREATE TABLE IF NOT EXISTS tbl_eb_policy_signal (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source VARCHAR(10), theme TEXT, policy_title TEXT, link TEXT, published TIMESTAMPTZ,
  ticker VARCHAR(40) NOT NULL DEFAULT '', is_holding BOOLEAN NOT NULL DEFAULT false,
  alerted BOOLEAN NOT NULL DEFAULT false, guid VARCHAR(320) NOT NULL DEFAULT '',
  fetched_on TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_eb_policy UNIQUE (guid, ticker)
);

-- Watchlist - cloud copy of the local history.json _watchlist, so cloud jobs
-- (weekly brief, buying-moment alerts) can see what we hold and watch.
CREATE TABLE IF NOT EXISTS tbl_eb_watchlist (
  sym VARCHAR(20) PRIMARY KEY,
  name TEXT, sector TEXT,
  kind VARCHAR(10),                  -- 'supplier' (proven) or 'pioneer'; NULL = derive from data
  priority VARCHAR(8) NOT NULL DEFAULT '',   -- 'high' or ''
  held BOOLEAN NOT NULL DEFAULT false,       -- true = real money is in it
  noted DATE, noted_price DOUBLE PRECISION,
  why TEXT, flags TEXT, triggers TEXT,
  active BOOLEAN NOT NULL DEFAULT true,
  updated_on TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Alert log - per-name cooldown so the same buying-moment alert is not re-sent daily
CREATE TABLE IF NOT EXISTS tbl_eb_alert_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sym VARCHAR(20) NOT NULL, kind VARCHAR(20) NOT NULL,
  sent_on TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Trump news freshness: a story only surfaces once its true publish date is verified
ALTER TABLE tbl_eb_trump_news ADD COLUMN IF NOT EXISTS date_verified BOOLEAN NOT NULL DEFAULT false;

-- helpful indexes for the hot query paths
CREATE INDEX IF NOT EXISTS ix_eb_news_pub      ON tbl_eb_news (published);
CREATE INDEX IF NOT EXISTS ix_eb_trump_pub     ON tbl_eb_trump_news (published);
CREATE INDEX IF NOT EXISTS ix_eb_pool_fit      ON tbl_eb_pool (fit);
CREATE INDEX IF NOT EXISTS ix_eb_moves_3m      ON tbl_eb_moves (mv_3m);

-- RLS: deny-all on the public Data API; direct Postgres role bypasses it.
ALTER TABLE tbl_eb_universe        ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_eb_fundamentals    ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_eb_moves           ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_eb_news            ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_eb_sector_news     ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_eb_pool            ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_eb_sa_13f          ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_eb_sector_keywords ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_eb_keyword_log     ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_eb_trump_news      ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_eb_policy_signal   ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_eb_watchlist       ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_eb_alert_log       ENABLE ROW LEVEL SECURITY;
